[package]
name = "diplo"
version = "0.1.0"
edition = "2018"
description = "A script runner for deno made in rust™️"
authors = ["Tricked-dev"]
license = "Apache License 2.0"
readme = "README.md"


[dependencies]
clap = "3.0.0-beta.4"
dotenv = "0.15.0"
lazy_static = "1.4.0"
notify = "5.0.0-pre.13"
crossbeam-channel = "0.4.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
