# The URL the site will be built for
base_url = "https://diplo.ascella.wtf"
title = "Diplo"
description = "Diplo is a fast script runner and dependency manager for Deno written in rust"
theme = "adidoks"
default_language = "en"
compile_sass = true
generate_feed = true
minify_html = false
taxonomies = [
    { name = "authors" }, # Basic definition: no feed or pagination
]
build_search_index = true

[search]
include_title = true
include_description = false
include_content = true

[markdown]
highlight_code = true

[extra]
author = "tricked"
github = "https://github.com/tricked-dev"
email = "tricked@duck.com"

is_netlify = true
language_code = "en-US"
theme_color = "#fff"

title_separator = "|"    # set as |, -, _, etc
title_addition = "Diplo"

timeformat = "%B %e, %Y"      # e.g. June 14, 2021
timezone = "America/New_York"

edit_page = false
docs_repo = "https://github.com/tricked-dev/diplo"
repo_branch = "main"
math = false
library = "katex"                                  # options: "katex", "mathjax". default is "katex".
[extra.open]
enable = true
image = "doks.png"
twitter_site = "tricked"
twitter_creator = "tricked"
facebook_author = "tricked"
facebook_publisher = "tricked"
og_locale = "en_US"

[extra.schema]
type = "Organization"
logo = "logo-doks.png"
linked_in = ""
github = "https://github.com/tricked-dev"
section = "docs"                          # see config.extra.main~url
site_links_search_box = false

[[extra.menu.main]]
name = "Docs"
section = "docs"
url = "/docs/getting-started/introduction/"
weight = 10


[[extra.menu.social]]
name = "GitHub"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>'
url = "https://github.com/tricked-dev/diplo"
post = "v0.1.0"
weight = 20

[extra.footer]
info = 'Powered by <a href="https://www.netlify.com/">Netlify</a>, <a href="https://www.getzola.org/">Zola</a>, and <a href="https://github.com/aaranxu/adidoks">AdiDoks</a>'

[[extra.footer.nav]]
name = "Privacy"
url = "/privacy-policy/"
weight = 10
